### ISSUE TITLE
AbstractList should load naturalSearchConfig

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/natural#11]
The public property `NaturalAbstractList.naturalSearchConfig` exists but is never assigned in natural. We should refactor `NaturalSearchConfigurationService` that lives in each projects into an injection system that allow `NaturalAbstractList` to automatically load the configuration.

The current situation is that child class have to copy paste the following code:

```ts
this.naturalSearchConfig = naturalSearchConfigurationService.get(this.key);
```

Maybe something similar to:

```ts 
const iconsConfig: NaturalIconsConfig = {
    'qr': {
        svg: 'assets/icons/qr.svg',
    },
};

NaturalIconModule.forRoot(iconsConfig),
```

Except that we may have some restriction because we usually need to inject modelServices...

**Comment by sambaptista** [comment]
I had a reflexion about that, and decided to removed it. There's why :

`naturalSearchConfigurationService` is basically a very simple centralized array of project specific configurations without any added value logic. The only shorthand it brings is the bellow line :

```js
this.naturalSearchConfig = naturalSearchConfigurationService.get(this.key);
```

But `this.key` has been removed in v.0.0.16 dc016d090203e97aef86c307b45fc6742583d02f. `PersistenceService` uses now a url instead of key to avoid collisions between multiple instances of the same component. 

Imho I would replace `NaturalSearchConfigurationService` by a class `NaturalSearchConfigurationUtility` where some functions like `wrapLike`, `replaceOperatorByField` and `replaceOperatorByName` would be exported and this class could be included in `@ecodev/natural`.

In the consuming apps, we can preserve a centralized "index" of `DropdownConfigurations` into a single service (to avoid some injection duplication in listing components) but  I would dispatch the creation/management of the `listings of DropdownConfigurations` into the components themselves in ngOnInit for example. That would allow us to create contextual facets. There is not real need to centralize the listings as they are probably inapplicable to multiples types.

Last argument (if needed :)) is that for that single line mentioned above (that I would anyway remove), there is no need to add dependencies in super() call.
