### ISSUE TITLE
Ignore transparently unkown columns

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/natural#123]
If a user forge an URL, or if the column is removed from code but user still has that column in his preference, then we get a JS error like:

```
ERROR Error: Could not find column with id "quanqweqwetity".
```

Instead we should accept and ignore silently any unknown column name.

It's probably something to fix in `NaturalAbstractList.selectedColumns()`, somehow `this.selectedColumns = persistedColumns.split(',');` must be protected from unknown columns.

**Comment by sambaptista** [comment]
This issue is more complicated than meets the eye because there is a misconception.

The `ColumnPicker` is the only entity able to deal with the complexity related to available columns. 

But actually the list controler (`AbstractList`) is taking the sovereignty on it's child's ColumnPicker by providing directly the columns from the url to the `table` and ignoring the `ColumnsPicker`'s job.

The actual workflow is : 

* AbstractList read and parses columns from url
* AbstractList defines himself a variable that is provided to the `ColumnPicker` and to the `Table` with same getter.

The workflow should be : 

* AbstractList read and parses the columns from url
* AbstractList gives the columns to column-picker
* ColumnPicker do it's job considering only relevant columns
* ColumnsPicker emits an update event
* AbstractList stays idle while the table updates itself with the ColumnsPicker output.

I fear a fix would cause breaking change in template.

**Comment by PowerKiKi** [comment]
Breaking change in template is not necessarily a problem. They are typically easy to mass-edit across all projects at once. If the solution must break template usage, then so be it. I'll volunteer to upgrade our projects if need be.
